# 1/21/21
# R code to create proteomic heatmaps
#Updated 1/21/21 by MKellogg

# Adapted from script used by Natalie Cohen in "Dinoflagellates alter their carbon and nutrient metabolic strategies across environmental gradients in the central Pacific Ocean "
# code from https://github.com/cnatalie/metzyme
# Input file was generated by:
# 1. Exported Scaffold NSAF values (1%FDR, 3 min peptides, 99% peptide)
# 2. Averaged the counts of duplicate samples and multiplied all averages by 1000
# 3. Deleted proteins without PFAM annotations (unknown proteins)

# Set the working directory by going to Session->set WD-> choose directory

#Load necessary libraries
library(caroline)
library(pheatmap)
library(genefilter)
library(viridis)
library(RColorBrewer)
library(stringr)

#Load the dataset using read.csv
dataset = read.csv('HeatmapProteins.csv')

# Dataset contains duplicate labelled proteins (ex, there are 5 diff proteins annotated "Chlorophyll A/B Protein")
# Sum duplicate proteins by KOG Description. 'Name' is the column containing annotations
#Create a new dataset called "summed", give it the same column names as the original loaded dataset
#Co is in cols 2-7, Zn is in 8-13
summed = groupBy(dataset, by='Name',clmns=(8:13),aggregation='sum')
colnames(summed) = colnames(dataset[8:13])

#Create a new dataset called "curated" and apply log2(value) to all values
curated = summed
#m is ultimately what gets plotted
m= log2(curated+1)

#Calculates the variance across each row (indicated by 1, rather than column (2)
rowvar = apply(curated, 1, var)

#Get top 50 proteins with highest variance across the row
idx = names(rowvar[order(rowvar, decreasing = T)][1:50])

#Indicates that protein row labels are in column 1
annotation = data.frame(Sample = factor(1:6, labels = c('1')))
rownames(annotation) = colnames(m)
annotation$Sample = rownames(annotation)

#To flip dendrogram branch
callback = function(hc, mat){
  sv = svd(t(mat))$v[,1]
  dend = reorder(as.dendrogram(hc), wts = sv)
  as.hclust(dend)}

#Specify protein heatmap parameters
paletteLength = 50
myColor = colorRampPalette(brewer.pal(9, "YlGnBu"))(100)

#Create heatmap
pheatmap(m[idx,], color=myColor, 
         cluster_cols=F, fontsize_row=4, 
         cluster_rows=T, cellwidth=9, 
         cellheight=4, show_colnames=T, 
         show_rownames = T, legend = T,
         clustering_callback = callback, scale = 'row')
